version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build bootJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/databaselearninggame-0.0.1.jar
